//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace School_Management_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Faculty_Attendance
    {
        public int Faculty_ID { get; set; }
        public string Department { get; set; }
        public string Date { get; set; }
        public string Attendance { get; set; }
    }
}
