//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace School_Management_System.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class School_Management_SystemEntities : DbContext
    {
        public School_Management_SystemEntities()
            : base("name=School_Management_SystemEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Faculty_Attendance> Faculty_Attendance { get; set; }
        public virtual DbSet<Fee> Fees { get; set; }
        public virtual DbSet<New_Admission> New_Admission { get; set; }
        public virtual DbSet<Students_Attendance> Students_Attendance { get; set; }
        public virtual DbSet<Students_Marks> Students_Marks { get; set; }
    }
}
