//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace School_Management_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Students_Marks
    {
        public int Student_ID { get; set; }
        public string Subject { get; set; }
        public string Marks { get; set; }
    }
}
